//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricPineapple
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_User
    {
        public int gameID { get; set; }
        public int userID { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
    
        public virtual CVGSUser CVGSUser { get; set; }
        public virtual Game Game { get; set; }
        public virtual GameUserStatu GameUserStatu { get; set; }
    }
}
